packages:
  - apps/*
  - packages/internal/*
  - packages/*
onlyBuiltDependencies:
  - esbuild
catalog:
  '@eslint/js': ^9.39.1
  '@types/node': ^24.10.1
  eslint: ^9.39.1
  eslint-plugin-jsonc: ^2.21.0
  eslint-plugin-perfectionist: ^4.15.1
  eslint-plugin-pnpm: ^1.3.0
  eslint-plugin-react: ^7.37.5
  eslint-plugin-react-hooks: ^7.0.1
  eslint-plugin-turbo: ^2.6.1
  eslint-plugin-unused-imports: ^4.3.0
  globals: ^16.5.0
  jsonc-eslint-parser: ^2.4.1
  prettier: ^3.6.2
  rimraf: ^6.1.2
  tsup: ^8.5.1
  turbo: ^2.6.1
  typescript: ^5.9.3
  typescript-eslint: ^8.48.0
  yaml-eslint-parser: ^1.3.1
