packages:
  - apps/*
  - packages/internal/*
  - packages/*
onlyBuiltDependencies:
  - esbuild
catalog:
  '@eslint/js': ^9.39.1
  eslint: ^9.39.1
  eslint-plugin-perfectionist: ^4.15.1
  eslint-plugin-unused-imports: ^4.3.0
  globals: ^16.5.0
  prettier: ^3.6.2
  rimraf: ^6.1.2
  tsup: ^8.5.1
  turbo: ^2.6.1
  typescript: ^5.9.3
  typescript-eslint: ^8.47.0
